[tool.poetry]
name = "e-treasure-hunt"
version = "0.1.0"
description = ""
authors = ["David Hotham <david.hotham@blueyonder.co.uk>"]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^8.1.0"
django = "^3.1.8,<3.2"
djangorestframework = "^3.12.2"
geopy = "^2.0.0"
gunicorn = "^20.0.4"
holidays = "^0.11.1"
pytz = ">=2020.1"
requests = "^2.23.0"
whitenoise = "^5.2.0"

# Things needed for azure deployment.
django-storages = { version = "^1.9.1", extras = ["azure"] }
mssql-django = "^1.0b1"

# Things needed for heroku deployment.
# django-heroku = "^0.3.1"
# django-storages = { version = "^1.9.1", extras = ["dropbox"] }

[tool.poetry.dev-dependencies]
black = "^21.5b0"
django-stubs = "^1.5.0"
flake8 = "^3.7.9"
isort = "^5.4.2"
mypy = "^0.812"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
