[tool.poetry]
name = "e-treasure-hunt"
version = "0.1.0"
description = ""
authors = ["David Hotham <david.hotham@blueyonder.co.uk>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.4"
django-heroku = "^0.3.1"
django-storages = { version = "^1.9.1", extras = ["dropbox"] }
geopy = "^2.0.0"
gunicorn = "^20.0.4"
pytz = ">=2020.1"
requests = "^2.23.0"
holidays = "^0.10.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.7.9"
isort = "^5.4.2"
mypy = "^0.790"
django-stubs = "^1.5.0"

[tool.isort]
# Black compatible settings
# see https://github.com/psf/black#the-black-code-style
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
ensure_newline_before_comments=true
line_length=88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
