[tool.poetry]
name = "e-treasure-hunt"
version = "0.1.0"
description = ""
authors = ["David Hotham <david.hotham@blueyonder.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^9.1.1"
"backports.zoneinfo" = { version = "^0.2.1", python = "<3.9" }
django = "^4.0.5"
djangorestframework = "^3.13.1"
geopy = "^2.2.0"
gunicorn = "^20.1.0"
holidays = "^0.13"
whitenoise = "^6.1.0"

# Things needed for heroku deployment.
# django-heroku = "^0.3.1"
# django-storages = { version = "^1.9.1", extras = ["dropbox"] }

# Things needed for azure deployment.
azure-identity = "^1.10.0"
django-storages = { version = "^1.12.3", extras = ["azure"] }
mssql-django = "^1.1.3"

[tool.poetry.dev-dependencies]
black = ">=22.3.0"
django-stubs = ">=1.11.0"
djangorestframework-stubs = ">=1.6.0"
flake8 = ">=4.0.1"
isort = ">=5.10.1"
mypy = ">=0.950"
requests = ">=2.27.1"
types-backports = ">=0.1.3"
types-requests = ">=2.27.30"

[tool.black]
exclude = 'hunt/migrations'

[tool.isort]
profile = "black"
skip = 'hunt/migrations'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
enable_error_code = [
  "ignore-without-code",
  "redundant-expr",
  "truthy-bool",
]
show_error_codes = true
strict = true
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main"
]

[[tool.mypy.overrides]]
module = [
  "django_heroku.*",
  "geopy.*",
  "holidays.*",
  "zoneinfo.*",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "treasure.settings"
