[tool.poetry]
name = "e-treasure-hunt"
version = "0.1.0"
description = ""
authors = ["David Hotham <david.hotham@blueyonder.co.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
Pillow = "^9.2.0"
django = "^4.0.6"
djangorestframework = "^3.13.1"
geopy = "^2.2.0"
gunicorn = "^20.1.0"
holidays = "^0.14.2"
whitenoise = "^6.2.0"

# Things needed for azure deployment.
azure-identity = "^1.10.0"
django-storages = { version = "^1.12.3", extras = ["azure"] }
mssql-django = "^1.1.3"

[tool.poetry.dev-dependencies]
black = ">=22.6.0"
django-stubs = ">=1.12.0"
djangorestframework-stubs = ">=1.7.0"
flake8 = ">=4.0.1"
flake8-type-checking = ">=2.0.1"
isort = ">=5.10.1"
mypy = ">=0.961"
requests = ">=2.28.1"
types-backports = ">=0.1.3"
types-requests = ">=2.28.0"

[tool.black]
exclude = "hunt/migrations"

[tool.isort]
profile = "black"
skip = "hunt/migrations"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = "."
strict = true
enable_error_code = [
  "ignore-without-code",
  "redundant-expr",
  "truthy-bool",
]
show_error_codes = true
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main"
]

[[tool.mypy.overrides]]
module = [
  "holidays.*",
]
no_implicit_reexport = false

[[tool.mypy.overrides]]
module = [
  "geopy.*",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "treasure.settings"
