[tool.poetry]
name = "e-treasure-hunt"
version = "0.1.0"
description = ""
authors = ["David Hotham <david.hotham@blueyonder.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.1.0"
"backports.zoneinfo" = { version = "^0.2.1", python = "<3.9" }
django = "^3.2.5"
djangorestframework = "^3.12.2"
geopy = "^2.0.0"
gunicorn = "^20.0.4"
holidays = "^0.11.1"
whitenoise = "^5.2.0"

# Things needed for heroku deployment.
# django-heroku = "^0.3.1"
# django-storages = { version = "^1.9.1", extras = ["dropbox"] }

# Things needed for azure deployment.
azure-identity = "^1.6.0"
django-storages = { version = "^1.12", extras = ["azure"] }
mssql-django = "^1.0"

[tool.poetry.dev-dependencies]
black = "^21.5b0"
django-stubs = "^1.5.0"
djangorestframework-stubs = "^1.4.0"
flake8 = "^4.0.1"
isort = "^5.4.2"
mypy = "^0.910"
requests = "^2.26.0"
types-backports = "^0.1.3"
types-requests = "^2.25.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
module = "hunt.third_party.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "treasure.settings"
