name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os:
          - Ubuntu
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        include:
          - os: Ubuntu
            image: Ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install unixodbc-dev
        run: sudo apt-get install --yes --no-install-recommends unixodbc-dev

      - name: Set up python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install project
        run: poetry install

      - name: flake8
        run: poetry run flake8

      - name: mypy
        run: poetry run mypy .

      - name: isort
        run: poetry run isort --check .

      - name: black
        run: poetry run black --check .
